### ISSUE TITLE
traefik 访问 detector 发生 `write: broken pipe`

### ISSUE THREAD

**Issue by cospotato** [chaitin/traefik-safeline#1]
## 版本

- `traefik:v3.0.4`
- `traefik-safeline-plugin:v1.3.0`
- `safeline-detector`: `snserver 5.0.9-r2-0d62db6d`

## 报错

`traefik : : write tcp 10.97.172.218:32976->10.0.1.130:8000: write: broken pipe`

`traefik` 部署在 k8s 集群中，运行几分钟后就会出现上述报错，但是重启 traefik 后就会正常运行一段时间，又继续报错，一旦出现上述报错，雷池中就看不到任何的流量了。

ulimit 已经设置过了

```shell
root@6b9ba2ccc5ec:/# /detector/snserver -V
snserver 5.0.9-r2-0d62db6d
root@6b9ba2ccc5ec:/# ulimit -n
1073741816
root@6b9ba2ccc5ec:/# exit
exit
[root@safeline-demo safeline]# ulimit -n
65535
[root@safeline-demo safeline]#
```

进一步抓包显示 10s 发送了 28000+ 个 TCP 包，经过确认是 `Heartbeat` 的包

![CleanShot 2024-08-02 at 15 44 00@2x](https://github.com/user-attachments/assets/fe746639-8161-4479-b23a-f09e267ee3d5)
![CleanShot 2024-08-02 at 15 43 38@2x](https://github.com/user-attachments/assets/9cdbc021-c7a4-4169-8ea1-e6f4ec0de09f)

初步定位到问题代码是 https://github.com/chaitin/traefik-safeline/blob/eb8434cd3199eee1930a5a96e93279e27ee81de0/vendor/github.com/xbingW/t1k/server.go#L69-L71

此处的问题是从 chan 里取出 connection ，发送 heartbeat，然后放回 chan，又因为 chan 是有 buffer 的，所以非阻塞，紧接着又能从 chan 里拿出来，基本上永远走不到 default 里。

可能的修复方向是，调整发起 `Heartbeat()` 的方式，例如由每个 conn 自行管理 `Heartbeat()`，如果出现错误，自行退出，`Server` 对象只需要定期或者接受 conn 退出时的事件检查 Pool 中的 conn 数量是否足够，不足的补足即可。

## 预期

预期应该如 plugin 中配置的一样，每 20s 只发出 100 个心跳包。

**Comment by xbingW** [comment]
1.4.0 版本修复了

**Comment by wuyue92tree** [comment]
您好，我遇到了同样的问题，即使是更新到了1.4.0版本 @xbingW 

我的环境如下：
- safeline: 8.9.0 （snserver-engine 1.0.7-957e35dc8038aa0799a218a4b8fbd48944bb799c）
- traefik: v2.10.5 （部署与k3s集群）
- traefik-safeline-plugin: v1.4.0

@cospotato 您这边有试过1.4.0版本么，是否表现正常？

**Comment by cospotato** [comment]
@wuyue92tree 我这边发现 safeline 的问题太多，暂时下掉了

**Comment by Dicoders** [comment]
Hello, somebody resolved this problem? 
@cospotato can you tell me which waf solution you eventually switched to?
